# Configuration file for MegaLinter
IGNORE_GITIGNORED_FILES: true

# all, none, or list of linter keys
APPLY_FIXES: none
DISABLE_LINTERS:
  - COPYPASTE_JSCPD
  - REPOSITORY_DEVSKIM
  - SPELL_CSPELL
  - MARKDOWN_MARKDOWN_LINK_CHECK
  #  due to import-error
  - PYTHON_PYLINT
  - SPELL_LYCHEE
  - R_LINTR
  - REPOSITORY_DUSTILOCK
  # disabled for now, need to clean the code and re-enable later
  - PYTHON_MYPY
  - PYTHON_PYRIGHT
  - PYTHON_BLACK
  - PYTHON_ISORT

SHOW_ELAPSED_TIME: true

BASH_SHFMT_ARGUMENTS:
  - "--indent=2"
REPOSITORY_TRIVY_ARGUMENTS:
  - "--severity=MEDIUM,HIGH,CRITICAL"
REPOSITORY_KICS_ARGUMENTS:
  - --fail-on=HIGH
