version: "3"

env:
  COMPOSE_PROJECT_NAME: bzkf-onco-analytics-on-fhir

tasks:
  obds-to-fhir:
    dir: docker-compose/
    cmds:
      - |
        docker compose \
          -f compose.kafka.yaml \
          -f compose.decompose-xmls.yaml \
          -f compose.obds-to-fhir.yaml up --detach

  fhir-to-opal:
    dir: docker-compose/
    cmds:
      - |
        docker compose \
          -f compose.obds-fhir-to-opal.yaml up

  clean:
    dir: docker-compose/
    cmd: |
      docker compose -f compose.kafka.yaml down --volumes --remove-orphans
