fhirVersion: R4
fhirPathRules:
  - path: Resource.id
    method: cryptoHash
  - path: Bundle.entry.fullUrl
    method: cryptoHash
  - path: Bundle.entry.request.url
    method: cryptoHash
  - path: nodesByType('Reference').reference
    method: cryptoHash
  - path: nodesByType('Identifier').where(type.coding.where(system='http://terminology.hl7.org/CodeSystem/v2-0203' and code='VN').exists()).value
    method: cryptoHash
  - path: nodesByType('Identifier').where(type.coding.where(system='http://terminology.hl7.org/CodeSystem/v2-0203' and code='MR').exists()).value
    method: cryptoHash
parameters:
  dateShiftKey: ""
  dateShiftScope: resource
  cryptoHashKey: ""
  encryptKey: ""
  enablePartialAgesForRedact: true
  enablePartialDatesForRedact: true
  enablePartialZipCodesForRedact: true
  restrictedZipCodeTabulationAreas: []
