services:
  minio:
    image: ${IMAGE_REGISTRY_DOCKER_IO:-docker.io}/minio/minio:RELEASE.2025-09-07T16-13-09Z@sha256:14cea493d9a34af32f524e538b8346cf79f3321eff8e708c1e2960462bd8936e
    ipc: private
    command: server /data --console-address ":9001"
    environment:
      MINIO_UPDATE: "off"
      MINIO_CALLHOME_ENABLE: "off"
      MINIO_BROWSER: "on"
      MINIO_ROOT_USER: ${AWS_ACCESS_KEY_ID:?}
      MINIO_ROOT_PASSWORD: ${AWS_SECRET_ACCESS_KEY:?}
      MINIO_SCHEME: "http"
    volumes:
      - fhir-to-delta-minio-data:/data:rw
    ports:
      - "127.0.0.1:9001:9001"

  wait-for-minio:
    image: ${IMAGE_REGISTRY_DOCKER_IO:-docker.io}/curlimages/curl:8.19.0@sha256:9a6f6a17667960e077f1b153009aaf18ac99a622221084e1938a45a06fff057a
    ipc: none
    security_opt:
      - "no-new-privileges:true"
    cap_drop:
      - ALL
    privileged: false
    restart: "no"
    environment:
      S3_ENDPOINT_URL: http://minio:9000
    entrypoint: ["/bin/sh", "-c"]
    command:
      - |
        until [ "$(curl -s -o /dev/null -L -w "%{http_code}" "$$S3_ENDPOINT_URL/minio/health/live")" == "200" ]; do
            echo "$(date): Waiting for minio server @ $$S3_ENDPOINT_URL to be up";
            sleep 5;
        done;
    depends_on:
      minio:
        condition: service_started

  create-default-buckets:
    image: ${IMAGE_REGISTRY_DOCKER_IO:-docker.io}/minio/minio:RELEASE.2025-09-07T16-13-09Z@sha256:14cea493d9a34af32f524e538b8346cf79f3321eff8e708c1e2960462bd8936e
    restart: on-failure
    cap_drop:
      - ALL
    privileged: false
    ipc: none
    security_opt:
      - "no-new-privileges:true"
    depends_on:
      wait-for-minio:
        condition: service_completed_successfully
    entrypoint: ["/bin/bash", "-c"]
    environment:
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID:?}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY:?}
    command:
      - |
        /usr/bin/mc alias set minio http://minio:9000 $${AWS_ACCESS_KEY_ID} $${AWS_SECRET_ACCESS_KEY};
        /usr/bin/mc mb --ignore-existing minio/fhir;
        /usr/bin/mc mb --ignore-existing minio/spark-streaming-checkpoints;
        /usr/bin/mc mb --ignore-existing minio/results;

  kafka-fhir-to-delta:
    image: ${IMAGE_REGISTRY_GHCR_IO:-ghcr.io}/bzkf/fhir-to-lakehouse:v1.13.11@sha256:bc51a5d241e6fb5df82d4f788da06e3f8ff2f1a9b739320fc95f3d27ae43f2fd
    restart: unless-stopped
    cap_drop:
      - ALL
    privileged: false
    ipc: private
    security_opt:
      - "no-new-privileges:true"
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      SPARK_S3_ENDPOINT: minio:9000
      SPARK_CHECKPOINT_DIR: s3a://spark-streaming-checkpoints/fhir-to-lakehouse
      DELTA_DATABASE_DIR: "s3a://fhir/default"
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID:?}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY:?}
      KAFKA_TOPICS: ${FHIR_TO_DELTA_KAFKA_TOPICS:?}
      SPARK_DRIVER_MEMORY: ${SPARK_DRIVER_MEMORY:-8g}
    depends_on:
      wait-for-minio:
        condition: service_completed_successfully
    ports:
      - "127.0.0.1:4041:4040"

volumes:
  fhir-to-delta-minio-data: {}
