services:
  data-loader:
    image: docker.io/confluentinc/cp-kcat:8.2.3@sha256:b700209db34cc98a5a0287cdd49466e18c5736a5c51da02e237064868a3fec57
    ipc: none
    security_opt:
      - "no-new-privileges:true"
    cap_drop:
      - ALL
    privileged: false
    restart: on-failure
    entrypoint: ["/bin/bash", "-c"]
    command:
      - |
        for f in /data/demo-mii-bundles/*.json; do
          echo "$$f"
          tr -d '\n' < "$$f" | kcat -b kafka:9092 -t fhir.obds.bundles -P -k "$$f" -c 1
        done
    volumes:
      - ../tests/fixtures/fhir/:/data/demo-mii-bundles/:ro
    depends_on:
      wait-for-kafka:
        condition: service_completed_successfully

  wait-for-kafka:
    image: ghcr.io/wait4x/wait4x:3.7.1@sha256:4168ec1328e4fa51b82f7d601c18813b5e4aa85d0eda237cf3501b4ddd70d2c5
    ipc: none
    security_opt:
      - "no-new-privileges:true"
    cap_drop:
      - ALL
    privileged: false
    restart: "no"
    command:
      - kafka
      - kafka://kafka:9092
      - --timeout
      - 30s
    depends_on:
      kafka:
        condition: service_started
