services:
  fhir-gateway:
    image: ${IMAGE_REGISTRY_GHCR_IO:-ghcr.io}/miracum/fhir-gateway:v6.1.0@sha256:a8099b5df4f59bcfb6fbda7377542ac2f38555dc02210ad246b6d473b8604e84
    restart: unless-stopped
    cap_drop:
      - ALL
    ipc: none
    security_opt:
      - "no-new-privileges:true"
    read_only: true
    tmpfs:
      - /tmp
    privileged: false
    environment:
      SERVICES_PSQL_ENABLED: "false"
      SPRING_SQL_INIT_MODE: "never"
      SERVICES_PSEUDONYMIZER_ENABLED: "true"
      SERVICES_PSEUDONYMIZER_URL: "http://fhir-pseudonymizer:8080/fhir"
      SERVICES_LOINC_CONVERSIONS_ENABLED: "false"
      SERVICES_LOINC_CONVERSIONS_URL: ""
      SERVICES_FHIRSERVER_ENABLED: "false"
      MANAGEMENT_ENDPOINT_HEALTH_PROBES_ADD_ADDITIONAL_PATHS: "true"
      MANAGEMENT_SERVER_PORT: "8081"
      SERVICES_KAFKA_ENABLED: "true"
      KAFKA_INPUT_TOPICS: "fhir.obds.bundles"
      KAFKA_BOOTSTRAP_SERVERS: "kafka:9092"
      SERVICES_KAFKA_PROCESSOR_ENABLED: "true"
      SERVICES_KAFKA_PROCESSOR_CRYPTO_HASH_MESSAGE_KEYS_ENABLED: "true"
      SERVICES_KAFKA_PROCESSOR_CRYPTO_HASH_MESSAGE_KEYS_KEY: "${FHIR_PSEUDONYMIZER_CRYPTO_HASH_KEY:?}"
      SERVICES_KAFKA_PROCESSOR_GENERATE_OUTPUT_TOPIC_MATCH_EXPRESSION: "^fhir\\."
      SERVICES_KAFKA_PROCESSOR_GENERATE_OUTPUT_TOPIC_REPLACE_WITH: "fhir.pseudonymized."

  fhir-pseudonymizer:
    image: ${IMAGE_REGISTRY_GHCR_IO:-ghcr.io}/miracum/fhir-pseudonymizer:v2.25.0@sha256:e9ff406f538283e9be75a1595c3d797993278e6d8e126fd4f6e7105abb863acd
    restart: unless-stopped
    cap_drop:
      - ALL
    ipc: none
    security_opt:
      - "no-new-privileges:true"
    read_only: true
    privileged: false
    environment:
      DOTNET_EnableDiagnostics: "0"
      PseudonymizationService: "${FHIR_PSEUDONYMIZER_PSEUDONYMIZATION_SERVICE:-gPAS}"
      AnonymizationEngineConfigPath: "/etc/fhir-pseudonymizer/anonymization.yaml"
      Anonymization__CryptoHashKey: "${FHIR_PSEUDONYMIZER_CRYPTO_HASH_KEY:?}"
      gPAS__Url: ""
      gPAS__Auth__Basic__Username: ""
      gPAS__Auth__Basic__Password: ""
      gPAS__Version: "1.10.3"
    volumes:
      - ${FHIR_PSEUDONYMIZER_ANONYMIZATION_FILE_PATH:-?}:/etc/fhir-pseudonymizer/anonymization.yaml:ro
