services:
  obds-to-fhir:
    image: ${IMAGE_REGISTRY_GHCR_IO:-ghcr.io}/bzkf/obds-to-fhir:v3.0.0-beta.226@sha256:bae34b58362183929d2e5d7e1f919d3bc42413737430c3960fd093a16c6ec29f
    restart: unless-stopped
    cap_drop:
      - ALL
    privileged: false
    ipc: none
    security_opt:
      - "no-new-privileges:true"
    user: "65532:65532"
    environment:
      SECURITY_PROTOCOL: PLAINTEXT
      BOOTSTRAP_SERVERS: kafka:9092
      FHIR_OUTPUT_TOPIC_PARTITION_COUNT: "1"
      SPRING_CLOUD_STREAM_KAFKA_BINDER_MINPARTITIONCOUNT: "1"
      SPRING_CLOUD_STREAM_KAFKA_BINDER_AUTOADDPARTITIONS: "true"
      NUM_STREAM_THREADS: "1"
      FHIR_MAPPINGS_META_SOURCE: "obds-to-fhir"
