services:
  fhir-gateway:
    image: ghcr.io/miracum/fhir-gateway:v3.12.8@sha256:2cf2d887b25594c04af3d6be302f8ccaea12dee90965fe4e2f81d24786ac3b6d
    restart: unless-stopped
    cap_drop:
      - ALL
    ipc: none
    security_opt:
      - "no-new-privileges:true"
    read_only: true
    tmpfs:
      - /tmp
    privileged: false
    environment:
      SERVICES_PSQL_ENABLED: "false"
      SPRING_SQL_INIT_MODE: "never"
      SERVICES_PSEUDONYMIZER_ENABLED: "true"
      SERVICES_PSEUDONYMIZER_URL: "http://fhir-pseudonymizer:8080/fhir"
      SERVICES_LOINC_CONVERSIONS_ENABLED: "false"
      SERVICES_LOINC_CONVERSIONS_URL: ""
      SERVICES_FHIRSERVER_ENABLED: "false"
      MANAGEMENT_ENDPOINT_HEALTH_PROBES_ADD_ADDITIONAL_PATHS: "true"
      MANAGEMENT_SERVER_PORT: "8081"
      SERVICES_KAFKA_ENABLED: "true"
      INPUT_TOPIC: "fhir.obds.MedicationStatement,fhir.obds.Condition,fhir.obds.Observation,fhir.obds.Procedure,fhir.obds.Patient"
      OUTPUT_TOPIC: "fhir.post-gateway"
      BOOTSTRAP_SERVERS: "kafka:9092"
      SECURITY_PROTOCOL: "PLAINTEXT"
      SERVICES_KAFKA_GENERATE_OUTPUT_TOPIC_MATCH_EXPRESSION: "^fhir\\."
      SERVICES_KAFKA_GENERATE_OUTPUT_TOPIC_REPLACE_WITH: "fhir.pseudonymized."

  fhir-pseudonymizer:
    image: ghcr.io/miracum/fhir-pseudonymizer:v2.22.6@sha256:c2652779d173dba020305775da4f1a52ba7dae8c9bb51ab3595f20bd187ee936
    restart: unless-stopped
    cap_drop:
      - ALL
    ipc: none
    security_opt:
      - "no-new-privileges:true"
    read_only: true
    privileged: false
    environment:
      DOTNET_EnableDiagnostics: "0"
      PseudonymizationService: "${FHIR_PSEUDONYMIZER_PSEUDONYMIZATION_SERVICE:-gPAS}"
      AnonymizationEngineConfigPath: "/etc/fhir-pseudonymizer/anonymization.yaml"
      Anonymization__CryptoHashKey: "${FHIR_PSEUDONYMIZER_CRYPTO_HASH_KEY:?}"
      gPAS__Url: ""
      gPAS__Auth__Basic__Username: ""
      gPAS__Auth__Basic__Password: ""
      gPAS__Version: "1.10.3"
    volumes:
      - ./anonymization.yaml:/etc/fhir-pseudonymizer/anonymization.yaml:ro
