spark.io.compression.codec zstd
spark.io.compression.zstd.level 1
spark.sql.parquet.compression.codec zstd
parquet.compression.codec.zstd.level 9
spark.sql.extensions io.delta.sql.DeltaSparkSessionExtension
spark.sql.catalog.spark_catalog org.apache.spark.sql.delta.catalog.DeltaCatalog
spark.worker.cleanup.enabled true
spark.worker.cleanup.interval 60
spark.worker.cleanup.appDataTtl 60
spark.kafka.consumer.cache.capacity 1024
spark.sql.autoBroadcastJoinThreshold -1
spark.driver.extraJavaOptions -XX:+UseG1GC
spark.executor.extraJavaOptions -XX:+UseG1GC
