name: scheduled

on:
  repository_dispatch: {}
  workflow_dispatch: {}
  schedule:
    - cron: "00 18 * * *"

permissions:
  contents: read

jobs:
  schedule:
    uses: miracum/.github/.github/workflows/standard-schedule.yaml@0b72274fb79ff2e45b917bdb7426f575e2e2e0ea # v1.17.0
    permissions:
      contents: read
      issues: write
      security-events: write
    with:
      images: "['ghcr.io/bzkf/onco-analytics-on-fhir/decompose-xmls:latest', 'ghcr.io/bzkf/onco-analytics-on-fhir/obds-fhir-to-opal:latest']"
    secrets:
      github-token: ${{ secrets.GITHUB_TOKEN }}
