name: scheduled

on:
  repository_dispatch: {}
  workflow_dispatch: {}
  schedule:
    - cron: "00 18 * * *"

permissions:
  contents: read

jobs:
  schedule:
    uses: miracum/.github/.github/workflows/standard-schedule.yaml@9e83a2b0b2e5681d913d4decdd18ac4ad6a6091c # v1.18.0
    permissions:
      contents: read
      issues: write
      security-events: write
    with:
      images: "['ghcr.io/bzkf/onco-analytics-on-fhir/decompose-xmls:latest', 'ghcr.io/bzkf/onco-analytics-on-fhir/obds-fhir-to-opal:latest']"
    secrets:
      github-token: ${{ secrets.GITHUB_TOKEN }}
