name: scheduled

on:
  repository_dispatch: {}
  workflow_dispatch: {}
  schedule:
    - cron: "00 18 * * *"

permissions:
  contents: read

jobs:
  schedule:
    uses: miracum/.github/.github/workflows/standard-schedule.yaml@61598243fff8ce6ef7bd312e26d586b2dd10d7b3 # v1.16.23
    permissions:
      contents: read
      issues: write
      security-events: write
    with:
      images: "['ghcr.io/bzkf/onco-analytics-on-fhir/decompose-xmls:latest', 'ghcr.io/bzkf/onco-analytics-on-fhir/obds-fhir-to-opal:latest']"
    secrets:
      github-token: ${{ secrets.GITHUB_TOKEN }}
